---
sudo: required
language: python
python: "2.7"

env:
  - SITE=test.yml

before_install:
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible
script:
  # Check the role/playbook's syntax.
  - "ansible-playbook --syntax-check playbook.yml.example -i hosts"
