---

- name: install virtualenv
  apt: name=python-virtualenv state=present
  tags: monitoring

- name: install docker-compose
  pip: name=docker-compose virtualenv=/home/{{monitoring_user}}/docker-compose-ve state=present
  tags: monitoring
